jobs:
  include:
    - stage: build
      os: osx
      language: node_js
      node_js:
        - 12
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER=$HOME/.cache/electron-builder
      script:
        - npm install -g @vue/cli
        - npm install
        - npm run test:unit
      before_deploy:
        - export PACKAGE_VERSION=$(npm run --silent version)
        - export TRAVIS_TAG=${PACKAGE_VERSION}.${TRAVIS_BUILD_NUMBER}
        - echo $TRAVIS_TAG
        - git tag $TRAVIS_TAG
        - npm run electron:build
        - export RELEASE_NAME=${TRAVIS_OS_NAME}-${TRAVIS_TAG}.tar.gz
        - tar czvf ${RELEASE_NAME} dist_electron/
      deploy:
        provider: releases
        api_key:
          secure: NTNjBhh2Fzc8D9T6rFcq8YD8jzIpojHLglKvYvWCQrgo+J8kWfqtWuqrHWQAUjyM7pgwDCoN2UtwviHxXlNvQU+y/c+1orODXAZqvXPMQRcLBcJqsGmOwuBgUosaBvwmAKPGnB4Vun270u3dnHKKAbYN7JKNrI2L4eUcHVEwmuJKEH/Trf4X/uTp68FKZlEJqb6hMEqTZnJCybtY/XQ7qjS/SitojBog2Ub06PGM8dEVZBa/SBq410TqzfnNkYRUN2tCkhBmoD27kVqEcwVGtnp/66P6xMdXW2AsuIOLskMcEYplnT4V1FmlHTJGiMxJzmvUthUKeGiRUPHYrXJDpfofN3FZNPb3UAnjScxa59yLfIk6pRItXSM7Oda4g6FMfjEKSio8+TMdcMFrNLlyBJc2rrGGikYp02ATJUDPTqtUW7JyTMctqn+nfv+3Hm42ssQupFAmSdDLOoQUGQEvlaKQydgXsmHXDUBcH9tSJl+jCaSHqu8K5A62OkD0Kx6tW2fAb0uPuCM6F8Gm0O6TDzphSjwm4lLBCCJoWDsAC9xH8Kw4ydTcTKOShK8s6VckAwfFXVwgieZvJSLYrsqhqIezTidYvg6RP75hE1P+al2k91dThmr1bCl01Idn4o/dXf0RvlBaddNQ+GaJJdTHE+2QKlU9Ol2f2AS+jv7RXLA=
        skip_cleanup: true
        file_glob: true
        file: "${RELEASE_NAME}"
        tag_name: "$TRAVIS_TAG"
        draft: true
        on:
          branch: travis-update

    - stage: build
      os: windows
      language: node_js
      node_js:
        - 12
      env:
      - ELECTRON_CACHE=$HOME/.cache/electron
      - ELECTRON_BUILDER=$HOME/.cache/electron-builder
      script:
        - npm install -g @vue/cli
        - npm install
        - npm run test:unit
      before_deploy:
        - export PACKAGE_VERSION=$(npm run --silent version)
        - export TRAVIS_TAG=${PACKAGE_VERSION}.${TRAVIS_BUILD_NUMBER}
        - echo $TRAVIS_TAG
        - git tag $TRAVIS_TAG
        - npm run electron:build
        - export RELEASE_NAME=${TRAVIS_OS_NAME}-${TRAVIS_TAG}.tar.gz
        - tar czvf ${RELEASE_NAME} dist_electron/
      deploy:
        provider: releases
        api_key:
          secure: NTNjBhh2Fzc8D9T6rFcq8YD8jzIpojHLglKvYvWCQrgo+J8kWfqtWuqrHWQAUjyM7pgwDCoN2UtwviHxXlNvQU+y/c+1orODXAZqvXPMQRcLBcJqsGmOwuBgUosaBvwmAKPGnB4Vun270u3dnHKKAbYN7JKNrI2L4eUcHVEwmuJKEH/Trf4X/uTp68FKZlEJqb6hMEqTZnJCybtY/XQ7qjS/SitojBog2Ub06PGM8dEVZBa/SBq410TqzfnNkYRUN2tCkhBmoD27kVqEcwVGtnp/66P6xMdXW2AsuIOLskMcEYplnT4V1FmlHTJGiMxJzmvUthUKeGiRUPHYrXJDpfofN3FZNPb3UAnjScxa59yLfIk6pRItXSM7Oda4g6FMfjEKSio8+TMdcMFrNLlyBJc2rrGGikYp02ATJUDPTqtUW7JyTMctqn+nfv+3Hm42ssQupFAmSdDLOoQUGQEvlaKQydgXsmHXDUBcH9tSJl+jCaSHqu8K5A62OkD0Kx6tW2fAb0uPuCM6F8Gm0O6TDzphSjwm4lLBCCJoWDsAC9xH8Kw4ydTcTKOShK8s6VckAwfFXVwgieZvJSLYrsqhqIezTidYvg6RP75hE1P+al2k91dThmr1bCl01Idn4o/dXf0RvlBaddNQ+GaJJdTHE+2QKlU9Ol2f2AS+jv7RXLA=
        skip_cleanup: true
        file_glob: true
        file: "${RELEASE_NAME}"
        tag_name: "$TRAVIS_TAG"
        draft: true
        on:
          branch: travis-update

    - stage: build
      os: linux
      language: node_js
      node_js: 
        - 12
      env:
      - ELECTRON_CACHE=$HOME/.cache/electron
      - ELECTRON_BUILDER=$HOME/.cache/electron-builder
      script:
        - npm install -g @vue/cli
        - npm install
        - npm run test:unit
      before_deploy:
        - export PACKAGE_VERSION=$(npm run --silent version)
        - export TRAVIS_TAG=${PACKAGE_VERSION}.${TRAVIS_BUILD_NUMBER}
        - echo $TRAVIS_TAG
        - git tag $TRAVIS_TAG
        - npm run electron:build
        - export RELEASE_NAME=${TRAVIS_OS_NAME}-${TRAVIS_TAG}.tar.gz
        - tar czvf ${RELEASE_NAME} dist_electron/
      deploy:
        provider: releases
        api_key:
          secure: NTNjBhh2Fzc8D9T6rFcq8YD8jzIpojHLglKvYvWCQrgo+J8kWfqtWuqrHWQAUjyM7pgwDCoN2UtwviHxXlNvQU+y/c+1orODXAZqvXPMQRcLBcJqsGmOwuBgUosaBvwmAKPGnB4Vun270u3dnHKKAbYN7JKNrI2L4eUcHVEwmuJKEH/Trf4X/uTp68FKZlEJqb6hMEqTZnJCybtY/XQ7qjS/SitojBog2Ub06PGM8dEVZBa/SBq410TqzfnNkYRUN2tCkhBmoD27kVqEcwVGtnp/66P6xMdXW2AsuIOLskMcEYplnT4V1FmlHTJGiMxJzmvUthUKeGiRUPHYrXJDpfofN3FZNPb3UAnjScxa59yLfIk6pRItXSM7Oda4g6FMfjEKSio8+TMdcMFrNLlyBJc2rrGGikYp02ATJUDPTqtUW7JyTMctqn+nfv+3Hm42ssQupFAmSdDLOoQUGQEvlaKQydgXsmHXDUBcH9tSJl+jCaSHqu8K5A62OkD0Kx6tW2fAb0uPuCM6F8Gm0O6TDzphSjwm4lLBCCJoWDsAC9xH8Kw4ydTcTKOShK8s6VckAwfFXVwgieZvJSLYrsqhqIezTidYvg6RP75hE1P+al2k91dThmr1bCl01Idn4o/dXf0RvlBaddNQ+GaJJdTHE+2QKlU9Ol2f2AS+jv7RXLA=
        skip_cleanup: true
        file_glob: true
        file: "${RELEASE_NAME}"
        tag_name: "$TRAVIS_TAG"
        draft: false
        on:
          branch: travis-update

# cache:
#   npm: true
#   directories:
#     - node_modules
#     - $HOME/.cache/electron
#     - $HOME/.cache/electron-builder

# script:
# - npm install -g @vue/cli
# - npm install
# - npm run test:unit
# before_deploy:
# - export PACKAGE_VERSION=$(npm run --silent version)
# - export TRAVIS_TAG=${PACKAGE_VERSION}.${TRAVIS_BUILD_NUMBER}
# - echo $TRAVIS_TAG
# - git tag $TRAVIS_TAG
# - npm run electron:build
# - export RELEASE_NAME=${TRAVIS_OS_NAME}-${TRAVIS_TAG}.tar.gz
# - tar czvf ${RELEASE_NAME} dist_electron/
