jobs:
  env:
  include:
    - stage: build
      os: osx
      language: node_js
      node_js: 12
      before_install:
        - unset CSC_LINK
        - unset CSC_KEY_PASSWORD
      script:
        - npm install
        - npm run lint
        - export PACKAGE_VERSION=$(npm run --silent version)
        - git tag ${PACKAGE_VERSION}
        - npm run package-release

    - stage: build
      os: windows
      language: node_js
      node_js: 12
      before_install:
        # Ref https://github.com/electron-userland/electron-builder/issues/3629#issuecomment-554126964
        - echo $CSC_LINK | base64 --decode > cert.p12
        - certutil -p $CSC_KEY_PASSWORD -importpfx ./cert.p12
        - CSC_LINK=./cert.p12
      script:
        - choco install zip
        - npm install
        - npm run lint
        - export PACKAGE_VERSION=$(npm run --silent version)
        - git tag ${PACKAGE_VERSION}
        - npm run package-release

    - stage: build
      os: linux
      language: node_js
      node_js: 12
      before_install:
        - unset CSC_LINK
        - unset CSC_KEY_PASSWORD
      script:
        - sudo apt install zip
        - npm install
        - npm run lint
        - export PACKAGE_VERSION=$(npm run --silent version)
        - git tag ${PACKAGE_VERSION}
        - npm run package-release
      
      # Need this to be separate as it is the job that closes the release. Travis
      # likes to build in parallel, so this job needs to run last.
    - stage: deploy_builds
      os: linux
      language: node_js
      node_js: 12
      script:
        - export PACKAGE_VERSION=$(npm run --silent version)
        - git tag ${PACKAGE_VERSION}
      deploy:
        provider: releases
        api_key: ${GH_TOKEN}
        skip_cleanup: true
        tag_name: ${PACKAGE_VERSION}
        draft: false
        on:
          branch: auto-update
