jobs:
  env:
  include:
    - stage: build
      os: osx
      language: node_js
      node_js: 12
      before_install:
        - unset CSC_LINK
        - unset CSC_KEY_PASSWORD
      script:
        - npm install
        - npm run lint
        - export PACKAGE_VERSION=$(npm run --silent version)
        - git tag ${PACKAGE_VERSION}
        - if [ $TRAVIS_BRANCH  == "master" ]; then npm run package-release; else npm run package; fi

    - stage: build
      os: windows
      language: node_js
      node_js: 12
      before_install:
        # Ref https://github.com/electron-userland/electron-builder/issues/3629#issuecomment-554126964
        - echo $CSC_LINK | base64 --decode > cert.p12
        - certutil -p $CSC_KEY_PASSWORD -importpfx ./cert.p12
        - CSC_LINK=./cert.p12
      script:
        - choco install zip
        - npm install
        - npm run lint
        - export PACKAGE_VERSION=$(npm run --silent version)
        - git tag ${PACKAGE_VERSION}
        - if [ $TRAVIS_BRANCH  == "master" ]; then npm run package-release; else npm run package; fi

    - stage: build
      os: linux
      language: node_js
      node_js: 12
      before_install:
        - unset CSC_LINK
        - unset CSC_KEY_PASSWORD
      script:
        - sudo apt install zip
        - npm install
        - npm run lint
        - export PACKAGE_VERSION=$(npm run --silent version)
        - git tag ${PACKAGE_VERSION}
        - if [ $TRAVIS_BRANCH  == "master" ]; then npm run package-release; else npm run package; fi


