name: Build Moseq-Reports

on:
  push:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-latest, macos-latest, windows-latest]
        os: [windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: Prep Windows Cert
        with: # Set the secret as an input
          WINDOWS_CERTIFICATE_P12: ${{ secrets.WINDOWS_CERTIFICATE_P12 }}
          WINDOWS_CERTIFICATE_PSWD: ${{ secrets.WINDOWS_CERTIFICATE_PSWD }}
        if: ${{ runner.os == 'Windows' }}
        # Ref https://github.com/electron-userland/electron-builder/issues/3629#issuecomment-554126964
        run: |
          echo $WINDOWS_CERTIFICATE_P12 | base64 --decode > cert.p12
          certutil -p $WINDOWS_CERTIFICATE_PSWD -importpfx ./cert.p12
          echo CSC_LINK=./cert.p12 >> $GITHUB_ENV
          echo CSC_KEY_PASSWORD=WINDOWS_CERTIFICATE_PSWD >> $GITHUB_ENV

      # - name: Prep OSX Cert
      #   if: ${{ runner.os == 'macOS' }}
      #   run: |
      #     unset CSC_LINK
      #     unset CSC_KEY_PASSWORD

      # - name: Prep Linux Cert
      #   if: ${{ runner.os == 'Linux' }}
      #   run: |
      #     unset CSC_LINK
      #     unset CSC_KEY_PASSWORD


      - name: Install
        run: npm install

      - name: Version
        run: |
          echo PACKAGE_VERSION=$(npm run --silent version) >> $GITHUB_ENV

      - name: Linting
        run: npm run lint

      - name: Git Tag
        run: git tag ${{ env.PACKAGE_VERSION }}

      - name: Package (release)
        if: ${{ github.ref == '/refs/heads/windows-sign-action' }}
        run: npm run package-release

      - name: Package (dev)
        if: ${{ github.ref != '/refs/heads/master' }}
        run: npm run package

