name: Build Moseq-Reports

on:
  push:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: Prep Windows Cert
        if: ${{ runner.os == 'Windows' }}
        # Ref https://github.com/electron-userland/electron-builder/issues/3629#issuecomment-554126964
        run: |
          echo $CSC_LINK | base64 --decode > cert.p12
          certutil -p $CSC_KEY_PASSWORD -importpfx ./cert.p12
          echo CSC_LINK=./cert.p12 >> $GITHUB_ENV

      - name: Prep OSX Cert
        if: ${{ runner.os == 'macOS' }}
        run: |
          unset CSC_LINK
          unset CSC_KEY_PASSWORD

      - name: Prep Linux Cert
        if: ${{ runner.os == 'Linux' }}
        run: |
          unset CSC_LINK
          unset CSC_KEY_PASSWORD


      - name: Install
        run: npm install

      - name: Version
        run: |
          echo PACKAGE_VERSION=$(npm run --silent version) >> $GITHUB_ENV

      - name: Linting
        run: npm run lint

      - name: Git Tag
        run: git tag ${{ env.PACKAGE_VERSION }}

      - name: Package (release)
        if: ${{ github.ref == '/refs/heads/master' }}
        run: npm run package-release

      - name: Package (dev)
        if: ${{ github.ref != '/refs/heads/master' }}
        run: npm run package

